### ISSUE TITLE
Extra line aﬀected when used with a region

### ISSUE THREAD

**Issue by mathrick** [remyferre/comment-dwim-2#10]
Hi, I just switched from `comment-dwim`, and I generally still use `cd2` primarily with a region. I've noticed that the next line after region is affected with `cd2`. Ie. with the steps below (`|` is the cursor and » « is the region):
```python
|foo = bar
 baz.call()
```
Mark the entire first line:
```python
»foo = bar«
|baz.call()
```
<kbd>M-;</kbd>
```python
 # foo = bar
|# baz.call()   <-- unexpected!
```
With `comment-dwim`, the result is as expected:
```python
 # foo = bar
|baz.call()
```

I use the "mark a line" workflow primarily since it's very easy with my CUA / transient mark setup, it's just <kbd>S-up</kbd> and <kbd>S-down</kbd>

**Comment by remyferre** [comment]
This is part of the default behavior of `comment-dwim-2` to "auto-expand" the region so it fully comments lines. See this gif:

![](http://remyferre.github.io/images/cd2-region-expand.gif)

The thing is, from emacs' point of view, your region does not look like this:
```
»foo = bar«
|baz.call()
```
but like this (the region stops at the point):
```
»foo = bar
«|baz.call()
```
which is why `comment-dwim-2` comments the second line too.

You have two ways to avoid this:

- Make use of the "auto-expand" feature and just select the last line partially (just like in the gif) to comment it.

- Disable the "auto-expand" feature to behave more like `comment-dwim`. This can be done with the following:
```
(setq cd2/region-command 'cd2/comment-or-uncomment-region)
```

**Comment by mathrick** [comment]
Ah, I see. I knew that the region actually ended on the following line, I just didn't want to make it confusing in my drawing, but I guess I should have :) If this is in fact a feature with a knob I can tweak, that makes perfect sense. I actively use the ability to comment out partial lines when I'm using comments to disable bits of logic, so that's an important use case for me. Thanks for the clarification!

**Comment by mathrick** [comment]
Hmm, I played with it a bit more, and I still think it should be considered a bug. Consider what the user sees:

![cd2-1-1](https://user-images.githubusercontent.com/179487/100649031-b0885380-32f6-11eb-8ac7-d92c8d32507d.png)
![cd2-1-2](https://user-images.githubusercontent.com/179487/100649041-b2eaad80-32f6-11eb-99bc-c39872dba9cf.png)

versus:

![cd2-2-1](https://user-images.githubusercontent.com/179487/100649064-bb42e880-32f6-11eb-8376-484bb8e6cadd.png)
![cd2-2-2](https://user-images.githubusercontent.com/179487/100649073-bda54280-32f6-11eb-8e20-4e616b9b5226.png)

In the latter case, it's clear there are partial lines, and the result is as expected. But in the former, the UI clearly communicates to the user that the region includes *only* those two lines. It's an implementation detail that it actually ends just before the start of the following line, and user-facing commands should (and generally do) take care of interpreting it correctly. It gets even worse when I select upwards:

![cd2-3-1](https://user-images.githubusercontent.com/179487/100650377-b121e980-32f8-11eb-9b6f-6e01fef45059.png)
![cd2-3-2](https://user-images.githubusercontent.com/179487/100650385-b54e0700-32f8-11eb-8701-8fe6e8ad660f.png)

As it is, with the default configuration, there's no way make `cd2` do what I want if I only want to target those lines without going out of my way to select the last line partially. I don't think anyone expects that, even if they want partial lines behaviour.

**Comment by remyferre** [comment]
hmm i see your point. The fix is quite easy to do but since it implies changing the default behavior I'd like to try it for a few days to see how it holds up and if there aren't any edge cases.

In the meantime you can try it for yourself by adding this to your init file:

```el
(defun cd2/comment-or-uncomment-lines ()
  "Toggle commenting on all the lines that the region spans."
  (if (eq (line-number-at-pos (point))
          (line-number-at-pos (mark)))
	(cd2/comment-or-uncomment-region)
      (comment-or-uncomment-region
	 (save-excursion (goto-char (region-beginning)) (line-beginning-position))
	 (if (= (region-end)
                (save-excursion (goto-char (region-end)) (line-beginning-position)))
	     (- (region-end) 1)
	   (save-excursion (goto-char (region-end)) (line-end-position))))))
```

I don't know when I will have time to release it. Keep the issue open and i'll keep you updated here.

**Comment by remyferre** [comment]
Hey,

The fix has been released in the new version of `comment-dwim-2`. Let me know if there are any problems.
